### ISSUE TITLE
自己数据跑的结果正常，但加入COCO2017和自己的数据一起跑就cost炸了

### ISSUE THREAD

**Issue by wgr573echo** [bubbliiiing/yolox-pytorch#86]
想在您的基础上改一个小样本目标检测模型出来，之前有用您的模型跑过自己的数据，结果都是正常的，但在加入了COCO2017（每个class选30张image）作为base class数据和自己的数据（novel class）一起训练，就出现以下错误：
RuntimeError: CUDA error: device kernel image is invalid
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
block: [0,0,0], thread: [3,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
调试发现好像问题出在cost非常大，且逐渐发散，导致最后dynamic_k那边bug。
参数和您默认的一致，class一共86个（base80，novel6），用的yolox_s文件。

**Comment by bubbliiiing** [comment]
classes path没改吧

**Comment by wgr573echo** [comment]
应该不是这个问题 我是在您原来的my_class文件上直接生成的新的class集合

**Comment by bubbliiiing** [comment]
在cls_train.txt里面的类别数很大，超出了train.py的索引。

**Comment by wgr573echo** [comment]
好的谢谢您 我试试把base class去掉一部分

**Comment by wgr573echo** [comment]
麻烦多问一句 您说的超出train.py的索引是指什么索引呀

**Comment by wgr573echo** [comment]
已经解决啦，问题出在了coco样例生成的时候，coco默认是id0留给background，导致了id索引存在1个位移，且超出了索引范围
